version: 1.0.{build}

# For RDP access be sure to set the environment variable APPVEYOR_RDP_PASSWORD 
# (in AppVeyor project settings)

# TODO: Add MSVC support
image: Visual Studio 2019

platform: x64

environment:
  matrix:
    - BUILD_SHARED: OFF
      COMPILER: cygwin

for:
  - matrix:
      only:
        - OQS_USE_OPENSSL: OFF
    before_build:
      - cmd: |-
             choco install openssl
             choco install -y strawberryperl
             SET "OPENSSL_ROOT_DIR=C:\OpenSSL-Win64"

# Uncomment to activate RDP debugging:
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\appveyor_build.bat'

before_test:
  - cmd: |-
         SET "PATH=C:\Python37;C:\Python37\Scripts;%PATH%"
         pip.exe install pytest pytest-xdist psutil

test_script:
  - cmd: |-
         cd %APPVEYOR_BUILD_FOLDER%
         echo "%PATH%"
         set PATH=%cd%;c:\cygwin64\bin;%PATH% && echo %PATH% && python oqs-test/try_connection.py doone

# Uncomment to be able to log in and check results / debug via RDP at the end of build
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

